work_dir: ./work_dir/recognition/kinetics_skeleton-sub/ST_GCN

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150 
  data_path: ../data/Kinetics/kinetics-skeleton-sub/train_data.npy
  label_path: ../data/Kinetics/kinetics-skeleton-sub/train_label.pkl
test_feeder_args:
  data_path: ../data/Kinetics/kinetics-skeleton-sub/val_data.npy
  label_path: ../data/Kinetics/kinetics-skeleton-sub/val_label.pkl

# model
model: net.motif_stgcn.Model
model_args:
  in_channels: 3
  num_class: 30
  dropout: 0
  edge_importance_weighting: True
  pyramid_pool: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
  vtdb_args:
    interc: 2
    gr: 4

# training
device: [0, 1]
batch_size: 64
test_batch_size: 64

#optim
optimizer: 'SGD'
base_lr: 0.1
step: [40, 70, 80]
num_epoch: 100


